// Laway-awayan — the deck.
// Every card is ONE clue phrase of exactly one or two words — nothing
// longer. There is no top/full-phrase split (see specs/001-laway-awayan
// for why): the mouther mouths this phrase silently, their team lip-reads
// it and shouts a guess. Every got-it is worth a flat +1 point,
// regardless of word count — see app.js.
const CATEGORIES = {
  "Big Mouth Basics": [
    { phrase: "Banana" }, { phrase: "Pizza" }, { phrase: "Umbrella" }, { phrase: "Elephant" },
    { phrase: "Toothbrush" }, { phrase: "Balloon" }, { phrase: "Spaghetti" }, { phrase: "Bicycle" },
    { phrase: "Sandwich" }, { phrase: "Pillow" }, { phrase: "Volcano" }, { phrase: "Butterfly" },
    { phrase: "Skateboard" }, { phrase: "Waterfall" }, { phrase: "Popcorn" }, { phrase: "Sunglasses" },
    { phrase: "Watermelon" }, { phrase: "Flashlight" }, { phrase: "Backpack" }, { phrase: "Rainbow" },
    { phrase: "Octopus" }, { phrase: "Trampoline" }, { phrase: "Refrigerator" }, { phrase: "Helicopter" },
    { phrase: "Toaster" }, { phrase: "Blender" }, { phrase: "Microwave" }, { phrase: "Vacuum" },
    { phrase: "Mirror" }, { phrase: "Candle" }, { phrase: "Lantern" }, { phrase: "Hammer" },
    { phrase: "Scissors" }, { phrase: "Stapler" }, { phrase: "Notebook" }, { phrase: "Calculator" },
    { phrase: "Telescope" }, { phrase: "Microscope" }, { phrase: "Compass" }, { phrase: "Anchor" },
    { phrase: "Ladder" }, { phrase: "Bucket" }, { phrase: "Broom" }, { phrase: "Sponge" },
    { phrase: "Kettle" }, { phrase: "Teapot" }, { phrase: "Cupcake" }, { phrase: "Donut" },
    { phrase: "Pretzel" }, { phrase: "Pancake" }, { phrase: "Waffle" }, { phrase: "Hotdog" },
    { phrase: "Hamburger" }, { phrase: "Taco" }, { phrase: "Burrito" }, { phrase: "Noodles" },
    { phrase: "Dumpling" }, { phrase: "Cookie" }, { phrase: "Muffin" }, { phrase: "Croissant" },
    { phrase: "Bagel" }, { phrase: "Marshmallow" }, { phrase: "Lollipop" }, { phrase: "Chocolate" },
    { phrase: "Cheese" }, { phrase: "Yogurt" }, { phrase: "Avocado" }, { phrase: "Pineapple" },
    { phrase: "Strawberry" }, { phrase: "Blueberry" }, { phrase: "Cactus" }, { phrase: "Sunflower" },
    { phrase: "Daisy" }, { phrase: "Mushroom" }, { phrase: "Acorn" }, { phrase: "Pinecone" },
    { phrase: "Snowflake" }, { phrase: "Icicle" }, { phrase: "Bubble" }, { phrase: "Firework" },
    { phrase: "Kite" }, { phrase: "Yo-yo" }, { phrase: "Puzzle" }, { phrase: "Domino" },
    { phrase: "Dice" }, { phrase: "Marbles" }, { phrase: "Crayon" }, { phrase: "Paintbrush" },
    { phrase: "Palette" }, { phrase: "Camera" }, { phrase: "Binoculars" }, { phrase: "Magnet" },
    { phrase: "Battery" }, { phrase: "Lightbulb" }, { phrase: "Clock" }, { phrase: "Envelope" },
    { phrase: "Suitcase" }, { phrase: "Wallet" }, { phrase: "Necklace" }, { phrase: "Trophy" }
  ],
  "Filipino Eats": [
    { phrase: "Adobo" }, { phrase: "Sinigang" }, { phrase: "Lechon" }, { phrase: "Halo-Halo" },
    { phrase: "Pancit" }, { phrase: "Lumpia" }, { phrase: "Sisig" }, { phrase: "Tocino" },
    { phrase: "Bibingka" }, { phrase: "Kwek Kwek" }, { phrase: "Taho" }, { phrase: "Balut" },
    { phrase: "Longganisa" }, { phrase: "Kare-Kare" }, { phrase: "Champorado" }, { phrase: "Turon" },
    { phrase: "Sorbetes" }, { phrase: "Dinuguan" }, { phrase: "Palabok" }, { phrase: "Tapsilog" },
    { phrase: "Buko Juice" }, { phrase: "Fishball" }, { phrase: "Isaw" }, { phrase: "Puto" },
    { phrase: "Menudo" }, { phrase: "Caldereta" }, { phrase: "Afritada" }, { phrase: "Bicol Express" },
    { phrase: "Laing" }, { phrase: "Pinakbet" }, { phrase: "Bulalo" }, { phrase: "Nilaga" },
    { phrase: "Tinola" }, { phrase: "Arroz Caldo" }, { phrase: "Lugaw" }, { phrase: "Goto" },
    { phrase: "Mami" }, { phrase: "Batchoy" }, { phrase: "Lomi" }, { phrase: "Sotanghon" },
    { phrase: "Pansit Malabon" }, { phrase: "Chicken Inasal" }, { phrase: "Liempo" }, { phrase: "Crispy Pata" },
    { phrase: "Lechon Kawali" }, { phrase: "Bagnet" }, { phrase: "Chicharon" }, { phrase: "Kutsinta" },
    { phrase: "Sapin-Sapin" }, { phrase: "Puto Bumbong" }, { phrase: "Biko" }, { phrase: "Suman" },
    { phrase: "Maja Blanca" }, { phrase: "Leche Flan" }, { phrase: "Ube Halaya" }, { phrase: "Buko Pandan" },
    { phrase: "Polvoron" }, { phrase: "Pastillas" }, { phrase: "Yema" }, { phrase: "Bukayo" },
    { phrase: "Ensaymada" }, { phrase: "Pandesal" }, { phrase: "Coconut Bread" }, { phrase: "Spanish Bread" },
    { phrase: "Monay" }, { phrase: "Otap" }, { phrase: "Broas" }, { phrase: "Tsokolate" },
    { phrase: "Salabat" }, { phrase: "Calamansi Juice" }, { phrase: "Gulaman" }, { phrase: "Ice Candy" },
    { phrase: "Banana Cue" }, { phrase: "Camote Cue" }, { phrase: "Maruya" }, { phrase: "Ukoy" },
    { phrase: "Kilawin" }, { phrase: "Kinilaw" }, { phrase: "Paksiw" }, { phrase: "Escabeche" },
    { phrase: "Relyeno" }, { phrase: "Embutido" }, { phrase: "Morcon" }, { phrase: "Bopis" },
    { phrase: "Papaitan" }, { phrase: "Bagoong" }, { phrase: "Patis" }, { phrase: "Atchara" },
    { phrase: "Daing" }, { phrase: "Tuyo" }, { phrase: "Danggit" }, { phrase: "Bangus" },
    { phrase: "Alimango" }, { phrase: "Talaba" }, { phrase: "Betamax" }, { phrase: "Adidas" },
    { phrase: "Walkman" }, { phrase: "Siopao" }, { phrase: "Siomai" }, { phrase: "Empanada" }
  ],
  "Star Power": [
    { phrase: "Beyonce" }, { phrase: "Manny Pacquiao" }, { phrase: "Taylor Swift" }, { phrase: "Dwayne Johnson" },
    { phrase: "Rihanna" }, { phrase: "Kobe Bryant" }, { phrase: "Oprah" }, { phrase: "Messi" },
    { phrase: "Adele" }, { phrase: "Elon Musk" }, { phrase: "Beckham" }, { phrase: "Madonna" },
    { phrase: "LeBron James" }, { phrase: "Shakira" }, { phrase: "Ronaldo" }, { phrase: "Jackie Chan" },
    { phrase: "Serena Williams" }, { phrase: "Drake" }, { phrase: "Ed Sheeran" }, { phrase: "Vice Ganda" },
    { phrase: "Darna" }, { phrase: "Judy Ann" }, { phrase: "Coco Martin" }, { phrase: "Brad Pitt" },
    { phrase: "Tom Cruise" }, { phrase: "Will Smith" }, { phrase: "Zendaya" }, { phrase: "Ariana Grande" },
    { phrase: "Justin Bieber" }, { phrase: "Selena Gomez" }, { phrase: "Billie Eilish" }, { phrase: "Bruno Mars" },
    { phrase: "Katy Perry" }, { phrase: "Lady Gaga" }, { phrase: "Jennifer Lopez" }, { phrase: "Dua Lipa" },
    { phrase: "Harry Styles" }, { phrase: "Sam Smith" }, { phrase: "Chris Hemsworth" }, { phrase: "Robert Downey" },
    { phrase: "Scarlett Johansson" }, { phrase: "Emma Watson" }, { phrase: "Tom Holland" }, { phrase: "Zac Efron" },
    { phrase: "Angelina Jolie" }, { phrase: "Leonardo DiCaprio" }, { phrase: "Meryl Streep" }, { phrase: "Denzel Washington" },
    { phrase: "Morgan Freeman" }, { phrase: "Samuel Jackson" }, { phrase: "Keanu Reeves" }, { phrase: "Johnny Depp" },
    { phrase: "Ryan Reynolds" }, { phrase: "Hugh Jackman" }, { phrase: "Michael Jordan" }, { phrase: "Neymar" },
    { phrase: "Usain Bolt" }, { phrase: "Michael Phelps" }, { phrase: "Simone Biles" }, { phrase: "Roger Federer" },
    { phrase: "Rafael Nadal" }, { phrase: "Novak Djokovic" }, { phrase: "Steph Curry" }, { phrase: "Kevin Durant" },
    { phrase: "Shaquille O'Neal" }, { phrase: "Muhammad Ali" }, { phrase: "Mike Tyson" }, { phrase: "Kathryn Bernardo" },
    { phrase: "Daniel Padilla" }, { phrase: "Anne Curtis" }, { phrase: "Kris Aquino" }, { phrase: "Willie Revillame" },
    { phrase: "Piolo Pascual" }, { phrase: "Sarah Geronimo" }, { phrase: "Regine Velasquez" }, { phrase: "Gary Valenciano" },
    { phrase: "Aga Muhlach" }, { phrase: "Dolphy" }, { phrase: "Nora Aunor" }, { phrase: "Vilma Santos" },
    { phrase: "Sharon Cuneta" }, { phrase: "Robin Padilla" }, { phrase: "John Lloyd" }, { phrase: "Bea Alonzo" },
    { phrase: "Marian Rivera" }, { phrase: "Dingdong Dantes" }, { phrase: "Angel Locsin" }, { phrase: "Toni Gonzaga" },
    { phrase: "Alden Richards" }, { phrase: "Maine Mendoza" }, { phrase: "James Reid" }, { phrase: "Nadine Lustre" },
    { phrase: "Liza Soberano" }, { phrase: "Enrique Gil" }, { phrase: "Michael Jackson" }, { phrase: "Whitney Houston" },
    { phrase: "Elton John" }, { phrase: "Eminem" }, { phrase: "Bill Gates" }, { phrase: "Steve Jobs" }
  ],
  "Screen Time": [
    { phrase: "Frozen" }, { phrase: "Moana" }, { phrase: "Encanto" }, { phrase: "Barbie" },
    { phrase: "Shrek" }, { phrase: "Titanic" }, { phrase: "Avatar" }, { phrase: "Aladdin" },
    { phrase: "Coco" }, { phrase: "Toy Story" }, { phrase: "Iron Man" }, { phrase: "Batman" },
    { phrase: "Zootopia" }, { phrase: "Ratatouille" }, { phrase: "Squid Game" }, { phrase: "Wednesday" },
    { phrase: "Inception" }, { phrase: "Gladiator" }, { phrase: "Minions" }, { phrase: "Up" },
    { phrase: "Cars" }, { phrase: "Jaws" }, { phrase: "Ted" }, { phrase: "Spider-Man" },
    { phrase: "Superman" }, { phrase: "Wonder Woman" }, { phrase: "Black Panther" }, { phrase: "Thor" },
    { phrase: "Hulk" }, { phrase: "Deadpool" }, { phrase: "Tangled" }, { phrase: "Brave" },
    { phrase: "Cinderella" }, { phrase: "Mulan" }, { phrase: "Rapunzel" }, { phrase: "Pinocchio" },
    { phrase: "Bambi" }, { phrase: "Dumbo" }, { phrase: "Peter Pan" }, { phrase: "Hercules" },
    { phrase: "Tarzan" }, { phrase: "Finding Nemo" }, { phrase: "Finding Dory" }, { phrase: "Inside Out" },
    { phrase: "Wall-E" }, { phrase: "Luca" }, { phrase: "Turning Red" }, { phrase: "Soul" },
    { phrase: "Onward" }, { phrase: "Elemental" }, { phrase: "Wish" }, { phrase: "Madagascar" },
    { phrase: "Ice Age" }, { phrase: "Rio" }, { phrase: "Sing" }, { phrase: "Trolls" },
    { phrase: "The Grinch" }, { phrase: "Home Alone" }, { phrase: "Matilda" }, { phrase: "Annie" },
    { phrase: "Grease" }, { phrase: "Mamma Mia" }, { phrase: "Coraline" }, { phrase: "Whiplash" },
    { phrase: "Parasite" }, { phrase: "Joker" }, { phrase: "Avengers" }, { phrase: "Justice League" },
    { phrase: "X-Men" }, { phrase: "Wolverine" }, { phrase: "Ant-Man" }, { phrase: "Doctor Strange" },
    { phrase: "Captain America" }, { phrase: "Black Widow" }, { phrase: "Star Wars" }, { phrase: "Jurassic Park" },
    { phrase: "Jumanji" }, { phrase: "Ghostbusters" }, { phrase: "Transformers" }, { phrase: "Fast Furious" },
    { phrase: "John Wick" }, { phrase: "Terminator" }, { phrase: "Matrix" }, { phrase: "Rocky" },
    { phrase: "Rambo" }, { phrase: "Die Hard" }, { phrase: "Harry Potter" }, { phrase: "Twilight" },
    { phrase: "Hunger Games" }, { phrase: "Divergent" }, { phrase: "Maze Runner" }, { phrase: "Narnia" },
    { phrase: "Get Out" }, { phrase: "Hereditary" }, { phrase: "Conjuring" }, { phrase: "Scream" },
    { phrase: "Halloween" }, { phrase: "Forrest Gump" }, { phrase: "Fight Club" }, { phrase: "Stranger Things" }
  ],
  "Wild Kingdom": [
    { phrase: "Giraffe" }, { phrase: "Penguin" }, { phrase: "Kangaroo" }, { phrase: "Crocodile" },
    { phrase: "Flamingo" }, { phrase: "Hedgehog" }, { phrase: "Chameleon" }, { phrase: "Peacock" },
    { phrase: "Gorilla" }, { phrase: "Jellyfish" }, { phrase: "Rhinoceros" }, { phrase: "Ostrich" },
    { phrase: "Squirrel" }, { phrase: "Tarsier" }, { phrase: "Carabao" }, { phrase: "Komodo Dragon" },
    { phrase: "Sea Turtle" }, { phrase: "Manta Ray" }, { phrase: "Anteater" }, { phrase: "Platypus" },
    { phrase: "Armadillo" }, { phrase: "Mongoose" }, { phrase: "Walrus" }, { phrase: "Lion" },
    { phrase: "Tiger" }, { phrase: "Bear" }, { phrase: "Wolf" }, { phrase: "Fox" },
    { phrase: "Deer" }, { phrase: "Moose" }, { phrase: "Bison" }, { phrase: "Buffalo" },
    { phrase: "Zebra" }, { phrase: "Hippo" }, { phrase: "Cheetah" }, { phrase: "Leopard" },
    { phrase: "Jaguar" }, { phrase: "Panther" }, { phrase: "Lynx" }, { phrase: "Cougar" },
    { phrase: "Koala" }, { phrase: "Panda" }, { phrase: "Sloth" }, { phrase: "Otter" },
    { phrase: "Beaver" }, { phrase: "Raccoon" }, { phrase: "Skunk" }, { phrase: "Badger" },
    { phrase: "Weasel" }, { phrase: "Ferret" }, { phrase: "Meerkat" }, { phrase: "Lemur" },
    { phrase: "Baboon" }, { phrase: "Chimpanzee" }, { phrase: "Orangutan" }, { phrase: "Gibbon" },
    { phrase: "Camel" }, { phrase: "Llama" }, { phrase: "Alpaca" }, { phrase: "Donkey" },
    { phrase: "Mule" }, { phrase: "Rooster" }, { phrase: "Turkey" }, { phrase: "Goose" },
    { phrase: "Swan" }, { phrase: "Owl" }, { phrase: "Eagle" }, { phrase: "Hawk" },
    { phrase: "Falcon" }, { phrase: "Vulture" }, { phrase: "Raven" }, { phrase: "Parrot" },
    { phrase: "Toucan" }, { phrase: "Hummingbird" }, { phrase: "Woodpecker" }, { phrase: "Pelican" },
    { phrase: "Stork" }, { phrase: "Crane" }, { phrase: "Heron" }, { phrase: "Puffin" },
    { phrase: "Dolphin" }, { phrase: "Whale" }, { phrase: "Shark" }, { phrase: "Stingray" },
    { phrase: "Seahorse" }, { phrase: "Starfish" }, { phrase: "Lobster" }, { phrase: "Squid" },
    { phrase: "Snail" }, { phrase: "Frog" }, { phrase: "Toad" }, { phrase: "Salamander" },
    { phrase: "Iguana" }, { phrase: "Gecko" }, { phrase: "Cobra" }, { phrase: "Python" },
    { phrase: "Rattlesnake" }, { phrase: "Tortoise" }, { phrase: "Porcupine" }, { phrase: "Hyena" }
  ],
  "Sports & Games": [
    { phrase: "Basketball" }, { phrase: "Swimming" }, { phrase: "Boxing" }, { phrase: "Push-Up" },
    { phrase: "Jump Rope" }, { phrase: "Patintero" }, { phrase: "Rope Pull" }, { phrase: "Sipa" },
    { phrase: "Piko" }, { phrase: "Bowling" }, { phrase: "Skateboarding" }, { phrase: "Yoga" },
    { phrase: "Volleyball" }, { phrase: "Badminton" }, { phrase: "Wrestling" }, { phrase: "Karate" },
    { phrase: "Cheer Dance" }, { phrase: "Arm Wrestle" }, { phrase: "Sepak Takraw" }, { phrase: "Chess" },
    { phrase: "Zumba" }, { phrase: "Marathon" }, { phrase: "Surfing" }, { phrase: "Soccer" },
    { phrase: "Baseball" }, { phrase: "Football" }, { phrase: "Rugby" }, { phrase: "Cricket" },
    { phrase: "Hockey" }, { phrase: "Golf" }, { phrase: "Tennis" }, { phrase: "Table Tennis" },
    { phrase: "Fencing" }, { phrase: "Archery" }, { phrase: "Cycling" }, { phrase: "Rowing" },
    { phrase: "Sailing" }, { phrase: "Diving" }, { phrase: "Skiing" }, { phrase: "Snowboarding" },
    { phrase: "Ice Skating" }, { phrase: "Curling" }, { phrase: "Bobsled" }, { phrase: "Gymnastics" },
    { phrase: "Weightlifting" }, { phrase: "Powerlifting" }, { phrase: "Sprinting" }, { phrase: "Hurdles" },
    { phrase: "Long Jump" }, { phrase: "High Jump" }, { phrase: "Pole Vault" }, { phrase: "Discus" },
    { phrase: "Javelin" }, { phrase: "Shot Put" }, { phrase: "Triathlon" }, { phrase: "Decathlon" },
    { phrase: "Rock Climbing" }, { phrase: "Mountain Biking" }, { phrase: "Skydiving" }, { phrase: "Bungee Jump" },
    { phrase: "Parkour" }, { phrase: "Cheerleading" }, { phrase: "Dodgeball" }, { phrase: "Kickball" },
    { phrase: "Hide Seek" }, { phrase: "Hopscotch" }, { phrase: "Jenga" }, { phrase: "Charades" },
    { phrase: "Poker" }, { phrase: "Blackjack" }, { phrase: "Bingo" }, { phrase: "Scrabble" },
    { phrase: "Monopoly" }, { phrase: "Checkers" }, { phrase: "Dominoes" }, { phrase: "Sungka" },
    { phrase: "Tumbang Preso" }, { phrase: "Taguan" }, { phrase: "Luksong Baka" }, { phrase: "Luksong Tinik" },
    { phrase: "Agawan Base" }, { phrase: "Tong-its" }, { phrase: "Mahjong" }, { phrase: "Darts" },
    { phrase: "Billiards" }, { phrase: "Water Polo" }, { phrase: "Handball" }, { phrase: "Lacrosse" },
    { phrase: "Judo" }, { phrase: "Taekwondo" }, { phrase: "Muay Thai" }, { phrase: "Kickboxing" },
    { phrase: "Sumo" }, { phrase: "Arnis" }, { phrase: "Snooker" }, { phrase: "Frisbee" },
    { phrase: "Ping Pong" }, { phrase: "Pilates" }, { phrase: "Crossfit" }, { phrase: "Spinning" }
  ],
  "Internet Famous": [
    { phrase: "Selfie" }, { phrase: "Viral Video" }, { phrase: "Hashtag" }, { phrase: "Livestream" },
    { phrase: "Group Chat" }, { phrase: "Meme" }, { phrase: "Podcast" }, { phrase: "Influencer" },
    { phrase: "Screenshot" }, { phrase: "Emoji" }, { phrase: "Wifi Password" }, { phrase: "Airdrop" },
    { phrase: "Ring Light" }, { phrase: "Voice Note" }, { phrase: "Blue Check" }, { phrase: "Data Plan" },
    { phrase: "QR Code" }, { phrase: "Trending" }, { phrase: "Buffering" }, { phrase: "Low Battery" },
    { phrase: "Airplane Mode" }, { phrase: "Slow Motion" }, { phrase: "Face Filter" }, { phrase: "Facebook" },
    { phrase: "Instagram" }, { phrase: "TikTok" }, { phrase: "YouTube" }, { phrase: "Twitter" },
    { phrase: "Snapchat" }, { phrase: "WhatsApp" }, { phrase: "Telegram" }, { phrase: "Messenger" },
    { phrase: "Discord" }, { phrase: "Reddit" }, { phrase: "Pinterest" }, { phrase: "LinkedIn" },
    { phrase: "Spotify" }, { phrase: "Netflix" }, { phrase: "Video Call" }, { phrase: "Text Message" },
    { phrase: "Direct Message" }, { phrase: "Comment Section" }, { phrase: "Like Button" }, { phrase: "Follow Button" },
    { phrase: "Unfollow" }, { phrase: "Unfriend" }, { phrase: "Block" }, { phrase: "Mute" },
    { phrase: "Notification" }, { phrase: "Dark Mode" }, { phrase: "Password Reset" }, { phrase: "Two Factor" },
    { phrase: "Incognito Mode" }, { phrase: "Private Browsing" }, { phrase: "Search Engine" }, { phrase: "Google Search" },
    { phrase: "Autocorrect" }, { phrase: "Autoplay" }, { phrase: "Loading Screen" }, { phrase: "Error Message" },
    { phrase: "Broken Link" }, { phrase: "Dead Battery" }, { phrase: "Power Bank" }, { phrase: "Bluetooth" },
    { phrase: "Airpods" }, { phrase: "Earbuds" }, { phrase: "Smartwatch" }, { phrase: "Selfie Stick" },
    { phrase: "Filter" }, { phrase: "Sticker" }, { phrase: "Reaction" }, { phrase: "Retweet" },
    { phrase: "Repost" }, { phrase: "Algorithm" }, { phrase: "Clickbait" }, { phrase: "Cringe" },
    { phrase: "Cancel Culture" }, { phrase: "Doxxing" }, { phrase: "Catfish" }, { phrase: "Ghosting" },
    { phrase: "Simp" }, { phrase: "Rizz" }, { phrase: "Sus" }, { phrase: "No Cap" },
    { phrase: "Slay" }, { phrase: "Bestie" }, { phrase: "Bruh" }, { phrase: "FOMO" },
    { phrase: "YOLO" }, { phrase: "Vibe Check" }, { phrase: "Main Character" }, { phrase: "NPC" },
    { phrase: "Deepfake" }, { phrase: "Chatbot" }, { phrase: "Crypto" }, { phrase: "NFT" },
    { phrase: "Bitcoin" }, { phrase: "Username" }, { phrase: "Sign Up" }, { phrase: "Subscribe" }
  ],
  "Places to Go": [
    { phrase: "Boracay" }, { phrase: "Palawan" }, { phrase: "Baguio" }, { phrase: "Tokyo" },
    { phrase: "Paris" }, { phrase: "New York" }, { phrase: "Dubai" }, { phrase: "Cebu" },
    { phrase: "Siargao" }, { phrase: "Batanes" }, { phrase: "Bali" }, { phrase: "Venice" },
    { phrase: "Sagada" }, { phrase: "Vigan" }, { phrase: "Bohol" }, { phrase: "Seoul" },
    { phrase: "London" }, { phrase: "Grand Canyon" }, { phrase: "Mount Fuji" }, { phrase: "Niagara Falls" },
    { phrase: "Antarctica" }, { phrase: "Machu Picchu" }, { phrase: "Sahara" }, { phrase: "Manila" },
    { phrase: "Quezon City" }, { phrase: "Makati" }, { phrase: "Davao" }, { phrase: "Iloilo" },
    { phrase: "Zamboanga" }, { phrase: "Tagaytay" }, { phrase: "Subic" }, { phrase: "Coron" },
    { phrase: "El Nido" }, { phrase: "Bangkok" }, { phrase: "Singapore" }, { phrase: "Hong Kong" },
    { phrase: "Beijing" }, { phrase: "Shanghai" }, { phrase: "Kyoto" }, { phrase: "Osaka" },
    { phrase: "Jakarta" }, { phrase: "Kuala Lumpur" }, { phrase: "Hanoi" }, { phrase: "Mumbai" },
    { phrase: "New Delhi" }, { phrase: "Sydney" }, { phrase: "Melbourne" }, { phrase: "Auckland" },
    { phrase: "Rome" }, { phrase: "Milan" }, { phrase: "Florence" }, { phrase: "Barcelona" },
    { phrase: "Madrid" }, { phrase: "Amsterdam" }, { phrase: "Berlin" }, { phrase: "Munich" },
    { phrase: "Vienna" }, { phrase: "Zurich" }, { phrase: "Geneva" }, { phrase: "Athens" },
    { phrase: "Santorini" }, { phrase: "Istanbul" }, { phrase: "Cairo" }, { phrase: "Marrakech" },
    { phrase: "Cape Town" }, { phrase: "Nairobi" }, { phrase: "Seville" }, { phrase: "Sao Paulo" },
    { phrase: "Buenos Aires" }, { phrase: "Lima" }, { phrase: "Bogota" }, { phrase: "Mexico City" },
    { phrase: "Toronto" }, { phrase: "Vancouver" }, { phrase: "Los Angeles" }, { phrase: "San Francisco" },
    { phrase: "Las Vegas" }, { phrase: "Chicago" }, { phrase: "Miami" }, { phrase: "Boston" },
    { phrase: "Hawaii" }, { phrase: "Alaska" }, { phrase: "Iceland" }, { phrase: "Norway" },
    { phrase: "Swiss Alps" }, { phrase: "Great Wall" }, { phrase: "Eiffel Tower" }, { phrase: "Big Ben" },
    { phrase: "Colosseum" }, { phrase: "Taj Mahal" }, { phrase: "Petra" }, { phrase: "Pyramids" },
    { phrase: "Stonehenge" }, { phrase: "Golden Gate" }, { phrase: "Hollywood Sign" }, { phrase: "Times Square" },
    { phrase: "Central Park" }, { phrase: "Disneyland" }, { phrase: "Angkor Wat" }, { phrase: "Mount Everest" }
  ],
  "Everyday Chaos": [
    { phrase: "Alarm Clock" }, { phrase: "Traffic Jam" }, { phrase: "Karaoke" }, { phrase: "Brownout" },
    { phrase: "Tricycle" }, { phrase: "Jeepney" }, { phrase: "Sari-Sari Store" }, { phrase: "Rubber Slippers" },
    { phrase: "Fiesta" }, { phrase: "Mosquito Net" }, { phrase: "Sack Race" }, { phrase: "Videoke" },
    { phrase: "Umbrella Stand" }, { phrase: "Parking Ticket" }, { phrase: "Extension Cord" }, { phrase: "Dishwashing Liquid" },
    { phrase: "Aircon Remote" }, { phrase: "Charging Cable" }, { phrase: "Grocery List" }, { phrase: "Piggy Bank" },
    { phrase: "Photobomb" }, { phrase: "Tissue Paper" }, { phrase: "House Key" }, { phrase: "Flat Tire" },
    { phrase: "Dead Phone" }, { phrase: "Lost Keys" }, { phrase: "Spilled Coffee" }, { phrase: "Overslept" },
    { phrase: "Missed Bus" }, { phrase: "Long Line" }, { phrase: "Wrong Number" }, { phrase: "Power Outage" },
    { phrase: "No Signal" }, { phrase: "Empty Fridge" }, { phrase: "Burnt Rice" }, { phrase: "Broken Umbrella" },
    { phrase: "Squeaky Shoes" }, { phrase: "Itchy Sweater" }, { phrase: "Tangled Earphones" }, { phrase: "Lost Remote" },
    { phrase: "Clogged Drain" }, { phrase: "Leaking Faucet" }, { phrase: "Broken Zipper" }, { phrase: "Missing Sock" },
    { phrase: "Paper Cut" }, { phrase: "Stubbed Toe" }, { phrase: "Brain Freeze" }, { phrase: "Hiccups" },
    { phrase: "Sneezing Fit" }, { phrase: "Sunburn" }, { phrase: "Mosquito Bite" }, { phrase: "Cockroach" },
    { phrase: "Rat Trap" }, { phrase: "Fly Swatter" }, { phrase: "Spider Web" }, { phrase: "Termites" },
    { phrase: "Leaky Roof" }, { phrase: "Squeaky Door" }, { phrase: "Flickering Light" }, { phrase: "Short Circuit" },
    { phrase: "Fuse Box" }, { phrase: "Water Bill" }, { phrase: "Electric Bill" }, { phrase: "Overdue Bill" },
    { phrase: "Credit Card" }, { phrase: "ATM Line" }, { phrase: "Long Queue" }, { phrase: "Road Rage" },
    { phrase: "Wrong Turn" }, { phrase: "Flat Battery" }, { phrase: "Empty Tank" }, { phrase: "Speed Bump" },
    { phrase: "Pothole" }, { phrase: "Detour Sign" }, { phrase: "No Parking" }, { phrase: "Towed Car" },
    { phrase: "Jaywalking" }, { phrase: "Rainy Commute" }, { phrase: "Sudden Downpour" }, { phrase: "Wet Socks" },
    { phrase: "Missed Alarm" }, { phrase: "Snooze Button" }, { phrase: "Group Project" }, { phrase: "Deadline" },
    { phrase: "Homework" }, { phrase: "Exam Week" }, { phrase: "Pop Quiz" }, { phrase: "Report Card" },
    { phrase: "Detention" }, { phrase: "Recess Bell" }, { phrase: "Lunch Line" }, { phrase: "Cafeteria Food" },
    { phrase: "School Uniform" }, { phrase: "Broken Pencil" }, { phrase: "Jammed Printer" }, { phrase: "Slow Wifi" },
    { phrase: "Frozen Screen" }, { phrase: "Blue Screen" }, { phrase: "Missed Call" }, { phrase: "Spam Call" }
  ]
};
